
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROPIEDADES = 15;
  public static final int FAMILIA = 4;
  public static final int NOTA_DE_PERFUME = 9;
  public static final int DATOS = 21;
  public static final int PERFUME = 10;
  public static final int SOLUBLE_EN = 11;
  public static final int DESCRIPCION_OLFATIVA = 7;
  public static final int EXTRACCION = 6;
  public static final int CONTRAINDICACIONES = 19;
  public static final int NOMBRE_LATINO = 3;
  public static final int USOS_GENERALES = 14;
  public static final int INDISOLUBLE_EN = 12;
  public static final int EOF = 0;
  public static final int PROCEDENCIA = 5;
  public static final int DATOS_QUE_NO_SE_USA = 22;
  public static final int USO = 20;
  public static final int AE = 2;
  public static final int BENEFICIOS_AROMATERAPEUTICOS = 16;
  public static final int SINERGIA = 17;
  public static final int error = 1;
  public static final int APARIENCIA = 8;
  public static final int PRECAUCIONES = 18;
  public static final int DESCRIPCION = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AE",
  "NOMBRE_LATINO",
  "FAMILIA",
  "PROCEDENCIA",
  "EXTRACCION",
  "DESCRIPCION_OLFATIVA",
  "APARIENCIA",
  "NOTA_DE_PERFUME",
  "PERFUME",
  "SOLUBLE_EN",
  "INDISOLUBLE_EN",
  "DESCRIPCION",
  "USOS_GENERALES",
  "PROPIEDADES",
  "BENEFICIOS_AROMATERAPEUTICOS",
  "SINERGIA",
  "PRECAUCIONES",
  "CONTRAINDICACIONES",
  "USO",
  "DATOS",
  "DATOS_QUE_NO_SE_USA"
  };
}

